from .user import User
from .department import Department
from .subject import Subject
from .resource import Resource
from .favorite import Favorite
from .download_history import DownloadHistory
from .attendance import Attendance
from .timetable import Timetable
from .attendance_settings import AttendanceSettings
